### ISSUE TITLE
Integrate color sensor - set color signature based on autonomous selector and alliance

### ISSUE THREAD

**Issue by Jay9971** [calhighrobotics/high_stakes_x#11]
Feature: manually assigning alliance color to the private field alliance_color of Intake class prior to match using the Screen.

Allows for the color sensor to know which color is the alliance color.

Requires changes made on the issue-10/color-sensor-intake branch (private field alliance_color is added).

Suggestion: Integrate it into the auton selector so that the alliance color is selected at the same time as the auton.

**Comment by absozero** [comment]
Redo of #37
